/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBeefyVault } from "./IBeefyVault";
export type { IExtraLending } from "./IExtraLending";
export type { IPool } from "./IPool";
export type { VotePreviewer } from "./VotePreviewer";
