/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface VotePreviewerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "beefyBoost"
      | "beefyVault"
      | "exa"
      | "externalVotes"
      | "extraLending"
      | "extraReserveId"
      | "gauge"
      | "pool"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "beefyBoost",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "beefyVault",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "exa", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "externalVotes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "extraLending",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "extraReserveId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "gauge", values?: undefined): string;
  encodeFunctionData(functionFragment: "pool", values?: undefined): string;

  decodeFunctionResult(functionFragment: "beefyBoost", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "beefyVault", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "exa", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "externalVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "extraLending",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "extraReserveId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gauge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pool", data: BytesLike): Result;
}

export interface VotePreviewer extends BaseContract {
  connect(runner?: ContractRunner | null): VotePreviewer;
  waitForDeployment(): Promise<this>;

  interface: VotePreviewerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  beefyBoost: TypedContractMethod<[], [string], "view">;

  beefyVault: TypedContractMethod<[], [string], "view">;

  exa: TypedContractMethod<[], [string], "view">;

  externalVotes: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  extraLending: TypedContractMethod<[], [string], "view">;

  extraReserveId: TypedContractMethod<[], [bigint], "view">;

  gauge: TypedContractMethod<[], [string], "view">;

  pool: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "beefyBoost"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "beefyVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "exa"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "externalVotes"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "extraLending"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "extraReserveId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "gauge"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pool"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
