/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISablierV2LockupLinear,
  ISablierV2LockupLinearInterface,
} from "../../../../contracts/periphery/Airdrop.sol/ISablierV2LockupLinear";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "sender",
            type: "address",
          },
          {
            internalType: "address",
            name: "recipient",
            type: "address",
          },
          {
            internalType: "uint128",
            name: "totalAmount",
            type: "uint128",
          },
          {
            internalType: "contract ERC20",
            name: "asset",
            type: "address",
          },
          {
            internalType: "bool",
            name: "cancelable",
            type: "bool",
          },
          {
            components: [
              {
                internalType: "uint40",
                name: "cliff",
                type: "uint40",
              },
              {
                internalType: "uint40",
                name: "total",
                type: "uint40",
              },
            ],
            internalType: "struct Durations",
            name: "durations",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "address",
                name: "account",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "fee",
                type: "uint256",
              },
            ],
            internalType: "struct Broker",
            name: "broker",
            type: "tuple",
          },
        ],
        internalType: "struct CreateWithDurations",
        name: "params",
        type: "tuple",
      },
    ],
    name: "createWithDurations",
    outputs: [
      {
        internalType: "uint256",
        name: "streamId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISablierV2LockupLinear__factory {
  static readonly abi = _abi;
  static createInterface(): ISablierV2LockupLinearInterface {
    return new Interface(_abi) as ISablierV2LockupLinearInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISablierV2LockupLinear {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ISablierV2LockupLinear;
  }
}
